# What is the name/brand of your app?
# This will show up as the brand in many popular frontends as well
# as Emails and the Administration framework
NAME: "Beavy App"

# Define a hard to guess random key to secure your cookies
# We recommend you use a key generator like
#      http://www.miniwebtool.com/django-secret-key-generator/
# leaving this empty and the app will fail to start
SECRET_KEY: ""

# You should provide a password salt to generate passwords with
# this again is just a random string of 5-10 characters long,
# you can use the same key generator as before
SECURITY_PASSWORD_SALT: ""

# A list of the modules you want to have activated
# modules are python-modules found in beavy_modules.*
MODULES:
 - comments
 - likes
 - private_messaging

# Which App do you want to load and compile into the UI?
# Apps are what ties your modules, backend and frontend together.
# The app is just another beavy-(python)-module but located in
# `beavy_apps` and loaded _after_ all modules have been.
# By default, beavy ships with a few examples. See the docs
APP: 'minima'


# Which url do you want to be the 'home' screen,
# the entry point of the app. Please read the
# docs on configuration
URLS:
  HOME: '/hello'
# You can also replace any other blueprint entry point here,
# like this:
#  USERS: '/nutzer'

# Which language do you want to serve as your apps' default
# localization language? The default is English.
# DEFAULT_LANGUAGE: 'en'

# Uncomment this to enable registrations
# SECURITY_REGISTERABLE: true


# Uncomment this, if you want to provide any social
# login capabilities. Please consult the docs if you
# you want to use this
# --------:
# SOCIAL_LOGINS:
#   Twitter:
#     consumer_key: XYZ
#     consumer_secret: LONGXYZ
#   Facebook:
#     consumer_key: XYZ
#     consumer_secret: LONGXYZ
