"""empty message

Revision ID: 5e83a31cef64
Revises: 32be118bfea
Create Date: 2016-03-27 13:01:35.765448

"""

# revision identifiers, used by Alembic.
revision = '5e83a31cef64'
down_revision = '32be118bfea'

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objects_belongs_to_fkey', 'objects', type_='foreignkey')
    op.alter_column('objects', 'belongs_to', new_column_name="belongs_to_id")
    op.create_foreign_key(None, 'objects', 'objects', ['belongs_to_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('objects_belongs_to_id_fkey', 'objects', type_='foreignkey')
    op.alter_column('objects', 'belongs_to_id', new_column_name="belongs_to")
    op.create_foreign_key(None, 'objects', 'objects', ['belongs_to'], ['id'])
    ### end Alembic commands ###
