"""empty message

Revision ID: ef0a325fcc3d
Revises: 5e83a31cef64
Create Date: 2016-03-27 13:12:59.045543

"""

# revision identifiers, used by Alembic.
revision = 'ef0a325fcc3d'
down_revision = '5e83a31cef64'

# add this here in order to use revision with branch_label
branch_labels = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('public', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'public')
    ### end Alembic commands ###
