= Database Migrations

All changes to database schema are handled with the link::http://alembic.readthedocs.org/en/latest/index.html[Alembic], wrapped by the link:https://flask-migrate.readthedocs.org/en/latest/[flask-migrate extension]. We have one linear database migration tree for all of mainline beavy, which includes the database schemas for – even deactivated – modules. The only case separate from this is, if your app provides further migrations.

== Running migrations

Before you do anything, make sure your database is on the latest stand. If you use any of our provided production environments, this happens automatically. In development however, you should _always activate all modules_ before you work with database migrations and make sure to be on the latest schema version by running:

```
python manager.py db upgrade heads
```

== Creating a new database migration

_Note_: make sure your database is on the latest version by running `python manager.py db migrate heads`

After you've made changes to the database models, you can automatically generate the new migrations by running the following command within your vagrant/virtual environment:

```
python manager.py db revision --autogenerate -m "Message Describing my changes"
```

This will create a new version in `migrations/versions`. Please review, and reformat it before applying or committing.

_Note_: If the migration deletes many more tables than you expected it to delete you might have not enabled all `beavy_modules` and alembic proposed to remove the tables as it couldn't find the models for. The recommended way is to always run the revision command only after you've (temporarily) added all modules in your config.

== Custom App Migrations

If your app really needs its own migrations outside of beavy itself, you can manage your own branch of migrations easily in your own fork.

=== Initialize Custom Migrations

After you've made your first set of changes, generate your migration-branch as follows. We are using the "MY-APP" as the branch label here:

```
python manager.py db revision --autogenerate -m "Branching our App" --branch MY-APP --head=beavy@head
```

This should generate a new migration in the `migrations/versions` folder.You can, if you want to, move that file into your own app-folder under `beavy_apps/$APP/migrations`, if you want to keep them separate. Open and review the contents of the file. You will notice that in the head it specifies the previously mentioned branch-label.

=== Add Custom Migrations

Once you have set up your own branch of changes, you can add more migrations by specifying that as head:

```
python manager.py db revision --autogenerate -m "My second app specific change" --head=MY-APP@head
```
